name       : python-paramiko
version    : 2.0.2
release    : 2
source     :
    - https://github.com/paramiko/paramiko/archive/2.0.2.tar.gz : 1c777729a1d101f8c24fccaad0b80cc224f11829bd71a91c5cb7bebe386770aa
license    : LGPL-2.1
component  : programming.python
summary    : Paramiko is a Python implementation of the SSHv2 protocol, providing
    both client and server functionality.
description: |
    Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-asn1
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
