name       : python-paramiko
version    : 2.4.2
release    : 4
source     :
    - https://github.com/paramiko/paramiko/archive/2.4.2.tar.gz : b3a3c22ed9ab6e12ac24cb2e81bf580af3b079b8ddb7438bd18851da4943599a
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality
description: |
    Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
builddeps  :
    - pkgconfig(python3)
    - python-bcrypt
    - python-cryptography
    - python-mock
    - python-pynacl
    - python-pytest
rundeps    :
    - python-bcrypt
    - python-cryptography
    - python-pynacl
setup      : |
    %patch -p1 < $pkgfiles/paramiko-2.4.2-drop-pytest-relaxed.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
