name       : python-paramiko
version    : 2.6.0
release    : 6
source     :
    - https://github.com/paramiko/paramiko/archive/2.6.0.tar.gz : 2da7c2431cfe60d77ffc427dd843779a2ce4549d5650889adfd978fdd0c45753
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Paramiko is a Python implementation of the SSHv2 protocol, providing
    both client and server functionality
description: |
    Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
builddeps  :
    - pkgconfig(python3)
    - python-bcrypt
    - python-cryptography
    - python-mock
    - python-pynacl
    - python-pytest
rundeps    :
    - python-bcrypt
    - python-cryptography
    - python-pynacl
setup      : |
    %patch -p1 < $pkgfiles/paramiko-2.6.0-drop-pytest-relaxed.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v
