name       : python-paramiko
version    : 2.0.8
release    : 3
source     :
    - https://github.com/paramiko/paramiko/archive/2.0.8.tar.gz : 45463cc641e068b4f8c8a600bb93d72e1b1dd3e1fdd01dc8e84c236a3f758aa0
license    : LGPL-2.1
component  : programming.python
summary    : Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
description: |
    Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - python-asn1
    - python-cryptography
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
