name       : python-paramiko
version    : 2.12.0
release    : 12
source     :
    - https://github.com/paramiko/paramiko/archive/2.12.0.tar.gz : 9cb87957e0afe8f88bf326c7dfbfbabd04324a1f4475a868450a4f7d9432b8c3
homepage   : https://www.paramiko.org/
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality
description: |
    Paramiko is a Python implementation of the SSHv2 protocol, providing both client and server functionality.
builddeps  :
    - python-bcrypt         # check
    - python-cryptography   # check
    - python-invoke         # check
    - python-mock           # check
    - python-pynacl         # check
    - python-pytest-relaxed # check
rundeps    :
    - python-bcrypt
    - python-cryptography
    - python-pynacl
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # upstream issue for failed tests https://github.com/paramiko/paramiko/issues/1941
    %python3_test py.test3 -v -k 'not (test_listdir_in_locale or attributes_locale_time)'
